### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by yucking** [DuYooho/HDM#1]
Is this the specific download link for this dataset?
![1730374637758](https://github.com/user-attachments/assets/373ab879-0ecc-48a5-8148-3a7aedf504a7)
![1730374787238](https://github.com/user-attachments/assets/5121790b-6aed-4120-91a2-28db9250b6b8)
Why is there no. pt file after extracting highlighted images from a 2D dataset?It's two folders, train and validation
And the test dataset downloaded from the repository above has multiple parallel files after decompression, followed by images and masks
![1730375667976](https://github.com/user-attachments/assets/41858ec2-29ec-4e9b-b552-d154f2ca15be)

**Comment by DuYooho** [comment]
Sorry for the typo; highlighted images should be `.png`. [#2f0e213](https://github.com/DuYooho/HDM/commit/2f0e213a048583b908488960009981d7e34dbb07)
